### ISSUE TITLE
Bug: Plugin Settings are empty

### ISSUE THREAD

**Issue by dsteppeler** [mLihs/svg-bem#1]
When I click on Plugins > SVG BEM > Open Settings a dialog opens that is just empty. When I do a right click I can Inspect the page. It ist just an HTML page with an empty body.

I am using Sketch V55.2 and just have a few plugins installed:
- Place Linked Bitmaps
- SVG BEM
- Unsplash

I would like to turn off BEM class names.

Thank you!

**Comment by tylerfawcett** [comment]
Experiencing this same issue.

**Comment by mLihs** [comment]
Fixed the issue :)
